name: Publish WAR package to GitHub

on:
    workflow_dispatch:

jobs:
    publishWar:
        runs-on: arc-runners-set
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Publish War file
              run: |
                  mvn deploy -s settings.xml
              env:
                  GITHUB_TOKEN: ${{ secrets.PAT }}
