name: Publish WAR package to GitHub

on:
    workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    publishWar:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Publish War file
              run: |
                  mvn deploy -s settings.xml
