name: "Test K8s Runners"

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v3

      - name: Say Hello
        run: |
          echo "Hello World - Running on k8s Self-hosted runners"
